// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(PockCoreFFI)
import PockCoreFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_pock_core_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_pock_core_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }

    init(rawBufferPointer: UnsafeRawBufferPointer) {
        self.init(
            len: Int32(rawBufferPointer.count),
            data: rawBufferPointer.baseAddress?.assumingMemoryBound(to: UInt8.self)
        )
    }
}

// Converter for `&[u8]` / `[ByRef] bytes` arguments.
//
// Conforms to `FfiConverter` so the compiler enforces the full converter
// method set. Only the scope-bound `lower(_:_body:)` overload is sound —
// zero-copy byte buffers only flow foreign -> Rust, and only in argument
// position. The four protocol-witness methods (`lift`, `lower`, `read`,
// `write`) `fatalError` at runtime if anyone reaches them.
//
// The scope-bound `lower` takes a closure because the `ForeignBytes`
// pointer is only guaranteed valid for the duration of
// `Data.withUnsafeBytes`. Callers must run the full FFI call inside
// the closure body.
fileprivate enum FfiConverterByRefBytes: FfiConverter {
    typealias SwiftType = Data
    typealias FfiType = ForeignBytes

    static func lower<R>(_ value: Data, _ body: (ForeignBytes) throws -> R) rethrows -> R {
        return try value.withUnsafeBytes { rawBuf in
            try body(ForeignBytes(rawBufferPointer: rawBuf))
        }
    }

    static func lower(_ value: Data) -> ForeignBytes {
        fatalError("ByRef bytes cannot use the plain lower: returning ForeignBytes escapes the Data.withUnsafeBytes scope. Use the scope-bound lower(_:_body:) overload instead.")
    }

    static func lift(_ value: ForeignBytes) throws -> Data {
        fatalError("ByRef bytes cannot be lifted: zero-copy &[u8] only flows foreign->Rust")
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        fatalError("ByRef bytes cannot be read from a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }

    static func write(_ value: Data, into buf: inout [UInt8]) {
        fatalError("ByRef bytes cannot be written to a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsurePockCoreInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        // Use Swift's native UTF-8 decoder; `String(bytes:encoding:.utf8)` goes
        // through Foundation's NSString and silently strips a leading U+FEFF BOM.
        // Invalid UTF-8 substitutes U+FFFD instead of trapping (unreachable
        // given Rust's `String` invariant).
        return String(decoding: bytes, as: UTF8.self)
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        // See `lift` above for why we avoid Foundation's NSString-backed decoder here.
        return String(decoding: try readBytes(&buf, count: Int(len)), as: UTF8.self)
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}


/**
 * The error Swift sees. Variants are coarse *categories* so a caller can
 * branch on "the user typed the wrong secret" versus "the caller passed
 * garbage" without string-matching. `message` is always the unchanged
 * `Display` text of the underlying [`CoreError`], so existing user-facing
 * strings survive verbatim.
 */
public 
enum PockCoreError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    /**
     * The supplied credential did not open the data.
     *
     * Covers a wrong passphrase, a wrong recovery code, a wrong Secret Key, a
     * failed platform-authenticator (Touch ID / PRF) unlock — **and AEAD
     * failures generally, which mean "wrong key *or* tampered ciphertext"**.
     * AEAD carries no way to tell those two apart, so do not present this to a
     * user as "wrong passphrase" unconditionally; on a decrypt path it may
     * equally mean the stored blob was corrupted or modified. Inspect
     * `message` for the specific wording when the distinction matters.
     */
    case WrongCredential(message: String
    )
    /**
     * The caller supplied a structurally invalid argument.
     */
    case InvalidInput(message: String
    )
    /**
     * A JSON payload could not be parsed or serialised.
     */
    case Json(message: String
    )
    /**
     * A base64 (or other encoding) payload could not be decoded.
     */
    case Encoding(message: String
    )
    /**
     * Anything else — cryptographic primitive failures that are not a wrong
     * credential (KDF, KEM, signature verification).
     */
    case Other(message: String
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension PockCoreError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePockCoreError: FfiConverterRustBuffer {
    typealias SwiftType = PockCoreError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PockCoreError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .WrongCredential(
            message: try FfiConverterString.read(from: &buf)
            )
        case 2: return .InvalidInput(
            message: try FfiConverterString.read(from: &buf)
            )
        case 3: return .Json(
            message: try FfiConverterString.read(from: &buf)
            )
        case 4: return .Encoding(
            message: try FfiConverterString.read(from: &buf)
            )
        case 5: return .Other(
            message: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: PockCoreError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .WrongCredential(message):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .InvalidInput(message):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .Json(message):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .Encoding(message):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .Other(message):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(message, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePockCoreError_lift(_ buf: RustBuffer) throws -> PockCoreError {
    return try FfiConverterTypePockCoreError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePockCoreError_lower(_ value: PockCoreError) -> RustBuffer {
    return FfiConverterTypePockCoreError.lower(value)
}
public func amkEnsure(passphrase: String, secretKeyB64: String, wrappedAukJson: String, existingWrappedAmk: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypePockCoreError_lift) {
        uniffiCallStatus in
    uniffi_pock_core_fn_func_amk_ensure(
        FfiConverterString.lower(passphrase),
        FfiConverterString.lower(secretKeyB64),
        FfiConverterString.lower(wrappedAukJson),
        FfiConverterString.lower(existingWrappedAmk),uniffiCallStatus
    )
})
}
public func amkEnsurePrf(prfSecretB64: String, wrappedAukPrfJson: String, existingWrappedAmk: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypePockCoreError_lift) {
        uniffiCallStatus in
    uniffi_pock_core_fn_func_amk_ensure_prf(
        FfiConverterString.lower(prfSecretB64),
        FfiConverterString.lower(wrappedAukPrfJson),
        FfiConverterString.lower(existingWrappedAmk),uniffiCallStatus
    )
})
}
public func amkSign(passphrase: String, secretKeyB64: String, wrappedAukJson: String, wrappedAmk: String, msg: Data)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypePockCoreError_lift) {
        uniffiCallStatus in
    uniffi_pock_core_fn_func_amk_sign(
        FfiConverterString.lower(passphrase),
        FfiConverterString.lower(secretKeyB64),
        FfiConverterString.lower(wrappedAukJson),
        FfiConverterString.lower(wrappedAmk),
        FfiConverterData.lower(msg),uniffiCallStatus
    )
})
}
public func amkSignPrf(prfSecretB64: String, wrappedAukPrfJson: String, wrappedAmk: String, msg: Data)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypePockCoreError_lift) {
        uniffiCallStatus in
    uniffi_pock_core_fn_func_amk_sign_prf(
        FfiConverterString.lower(prfSecretB64),
        FfiConverterString.lower(wrappedAukPrfJson),
        FfiConverterString.lower(wrappedAmk),
        FfiConverterData.lower(msg),uniffiCallStatus
    )
})
}
/**
 * Canonical bytes of `{userId,kemPubkey,signPubkey,rot,principalSeq,ts}`.
 */
public func certBytes(certJson: String)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypePockCoreError_lift) {
        uniffiCallStatus in
    uniffi_pock_core_fn_func_cert_bytes(
        FfiConverterString.lower(certJson),uniffiCallStatus
    )
})
}
public func changePassphrase(oldPassphrase: String, secretKeyB64: String, wrappedAukJson: String, newPassphrase: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypePockCoreError_lift) {
        uniffiCallStatus in
    uniffi_pock_core_fn_func_change_passphrase(
        FfiConverterString.lower(oldPassphrase),
        FfiConverterString.lower(secretKeyB64),
        FfiConverterString.lower(wrappedAukJson),
        FfiConverterString.lower(newPassphrase),uniffiCallStatus
    )
})
}
public func createVault(passphrase: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypePockCoreError_lift) {
        uniffiCallStatus in
    uniffi_pock_core_fn_func_create_vault(
        FfiConverterString.lower(passphrase),uniffiCallStatus
    )
})
}
/**
 * Create a vault with an explicit Argon2 profile ("native" | "constrained").
 */
public func createVaultProfile(passphrase: String, profileId: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypePockCoreError_lift) {
        uniffiCallStatus in
    uniffi_pock_core_fn_func_create_vault_profile(
        FfiConverterString.lower(passphrase),
        FfiConverterString.lower(profileId),uniffiCallStatus
    )
})
}
public func decryptItem(itemJson: String, identitySecretB64: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypePockCoreError_lift) {
        uniffiCallStatus in
    uniffi_pock_core_fn_func_decrypt_item(
        FfiConverterString.lower(itemJson),
        FfiConverterString.lower(identitySecretB64),uniffiCallStatus
    )
})
}
public func decryptShare(envelopeB64: String, keyBlob: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypePockCoreError_lift) {
        uniffiCallStatus in
    uniffi_pock_core_fn_func_decrypt_share(
        FfiConverterString.lower(envelopeB64),
        FfiConverterString.lower(keyBlob),uniffiCallStatus
    )
})
}
public func encryptItem(value: String, recipientPubBlobsJson: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypePockCoreError_lift) {
        uniffiCallStatus in
    uniffi_pock_core_fn_func_encrypt_item(
        FfiConverterString.lower(value),
        FfiConverterString.lower(recipientPubBlobsJson),uniffiCallStatus
    )
})
}
public func encryptShare(bundleJson: String, cipherId: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypePockCoreError_lift) {
        uniffiCallStatus in
    uniffi_pock_core_fn_func_encrypt_share(
        FfiConverterString.lower(bundleJson),
        FfiConverterString.lower(cipherId),uniffiCallStatus
    )
})
}
public func enrollPrf(passphrase: String, secretKeyB64: String, wrappedAukJson: String, prfSecretB64: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypePockCoreError_lift) {
        uniffiCallStatus in
    uniffi_pock_core_fn_func_enroll_prf(
        FfiConverterString.lower(passphrase),
        FfiConverterString.lower(secretKeyB64),
        FfiConverterString.lower(wrappedAukJson),
        FfiConverterString.lower(prfSecretB64),uniffiCallStatus
    )
})
}
public func exportBackup(json: String, passphrase: String)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypePockCoreError_lift) {
        uniffiCallStatus in
    uniffi_pock_core_fn_func_export_backup(
        FfiConverterString.lower(json),
        FfiConverterString.lower(passphrase),uniffiCallStatus
    )
})
}
public func generateIdentity() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_pock_core_fn_func_generate_identity(uniffiCallStatus
    )
})
}
public func generateSymmetricKey() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_pock_core_fn_func_generate_symmetric_key(uniffiCallStatus
    )
})
}
public func importBackup(data: Data, passphrase: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypePockCoreError_lift) {
        uniffiCallStatus in
    uniffi_pock_core_fn_func_import_backup(
        FfiConverterData.lower(data),
        FfiConverterString.lower(passphrase),uniffiCallStatus
    )
})
}
/**
 * Canonical bytes of `{userId,kemPubkey,signPubkey,ts}`.
 */
public func leafBytes(leafJson: String)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypePockCoreError_lift) {
        uniffiCallStatus in
    uniffi_pock_core_fn_func_leaf_bytes(
        FfiConverterString.lower(leafJson),uniffiCallStatus
    )
})
}
/**
 * `SHA-256(aad ‖ ct)` — the bytes a chat message signature covers.
 */
public func messageDigest(aad: Data, ct: Data) -> Data  {
    return try!  FfiConverterData.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_pock_core_fn_func_message_digest(
        FfiConverterData.lower(aad),
        FfiConverterData.lower(ct),uniffiCallStatus
    )
})
}
/**
 * Whether a stored value carries the `pns1.` prefix.
 */
public func nsIsProtected(blob: String) -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_pock_core_fn_func_ns_is_protected(
        FfiConverterString.lower(blob),uniffiCallStatus
    )
})
}
/**
 * Standard base64 of `SHA-256(nk)`, for the audit log.
 */
public func nsNkHash(nkB64: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypePockCoreError_lift) {
        uniffiCallStatus in
    uniffi_pock_core_fn_func_ns_nk_hash(
        FfiConverterString.lower(nkB64),uniffiCallStatus
    )
})
}
/**
 * Encrypt one value under the namespace key; result carries the `pns1.` prefix.
 */
public func nsProtectValue(nkB64: String, value: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypePockCoreError_lift) {
        uniffiCallStatus in
    uniffi_pock_core_fn_func_ns_protect_value(
        FfiConverterString.lower(nkB64),
        FfiConverterString.lower(value),uniffiCallStatus
    )
})
}
/**
 * A fresh namespace key, standard base64.
 */
public func nsRandomNk() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_pock_core_fn_func_ns_random_nk(uniffiCallStatus
    )
})
}
/**
 * A fresh namespace recovery code (`"a1b2-c3d4-…"`).
 */
public func nsRandomRecoveryCode() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_pock_core_fn_func_ns_random_recovery_code(uniffiCallStatus
    )
})
}
/**
 * A fresh 16-byte PBKDF2 salt, standard base64.
 */
public func nsRandomSalt() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_pock_core_fn_func_ns_random_salt(uniffiCallStatus
    )
})
}
/**
 * Decrypt a `pns1.` value under the namespace key.
 */
public func nsUnprotectValue(nkB64: String, blob: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypePockCoreError_lift) {
        uniffiCallStatus in
    uniffi_pock_core_fn_func_ns_unprotect_value(
        FfiConverterString.lower(nkB64),
        FfiConverterString.lower(blob),uniffiCallStatus
    )
})
}
/**
 * Unwrap the namespace key, returned as standard base64.
 */
public func nsUnwrapNk(wrapped: String, passphrase: String, saltB64: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypePockCoreError_lift) {
        uniffiCallStatus in
    uniffi_pock_core_fn_func_ns_unwrap_nk(
        FfiConverterString.lower(wrapped),
        FfiConverterString.lower(passphrase),
        FfiConverterString.lower(saltB64),uniffiCallStatus
    )
})
}
/**
 * Wrap the namespace key under a namespace passphrase.
 */
public func nsWrapNk(nkB64: String, passphrase: String, saltB64: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypePockCoreError_lift) {
        uniffiCallStatus in
    uniffi_pock_core_fn_func_ns_wrap_nk(
        FfiConverterString.lower(nkB64),
        FfiConverterString.lower(passphrase),
        FfiConverterString.lower(saltB64),uniffiCallStatus
    )
})
}
public func openSymmetric(keyB64: String, blob: Data, aad: Data)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypePockCoreError_lift) {
        uniffiCallStatus in
    uniffi_pock_core_fn_func_open_symmetric(
        FfiConverterString.lower(keyB64),
        FfiConverterData.lower(blob),
        FfiConverterData.lower(aad),uniffiCallStatus
    )
})
}
public func resetPassphrase(recoveryCode: String, wrappedRecoveryJson: String, secretKeyB64: String, newPassphrase: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypePockCoreError_lift) {
        uniffiCallStatus in
    uniffi_pock_core_fn_func_reset_passphrase(
        FfiConverterString.lower(recoveryCode),
        FfiConverterString.lower(wrappedRecoveryJson),
        FfiConverterString.lower(secretKeyB64),
        FfiConverterString.lower(newPassphrase),uniffiCallStatus
    )
})
}
public func rotateIdentity(passphrase: String, secretKeyB64: String, wrappedAukJson: String, oldWrappedIdentityB64: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypePockCoreError_lift) {
        uniffiCallStatus in
    uniffi_pock_core_fn_func_rotate_identity(
        FfiConverterString.lower(passphrase),
        FfiConverterString.lower(secretKeyB64),
        FfiConverterString.lower(wrappedAukJson),
        FfiConverterString.lower(oldWrappedIdentityB64),uniffiCallStatus
    )
})
}
public func rotateRecoveryCode(passphrase: String, secretKeyB64: String, wrappedAukJson: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypePockCoreError_lift) {
        uniffiCallStatus in
    uniffi_pock_core_fn_func_rotate_recovery_code(
        FfiConverterString.lower(passphrase),
        FfiConverterString.lower(secretKeyB64),
        FfiConverterString.lower(wrappedAukJson),uniffiCallStatus
    )
})
}
public func rotateSecretKey(passphrase: String, oldSecretKeyB64: String, wrappedAukJson: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypePockCoreError_lift) {
        uniffiCallStatus in
    uniffi_pock_core_fn_func_rotate_secret_key(
        FfiConverterString.lower(passphrase),
        FfiConverterString.lower(oldSecretKeyB64),
        FfiConverterString.lower(wrappedAukJson),uniffiCallStatus
    )
})
}
public func sealSymmetric(keyB64: String, plaintext: Data, aad: Data)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypePockCoreError_lift) {
        uniffiCallStatus in
    uniffi_pock_core_fn_func_seal_symmetric(
        FfiConverterString.lower(keyB64),
        FfiConverterData.lower(plaintext),
        FfiConverterData.lower(aad),uniffiCallStatus
    )
})
}
public func signMessage(identitySecretB64: String, msg: Data)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypePockCoreError_lift) {
        uniffiCallStatus in
    uniffi_pock_core_fn_func_sign_message(
        FfiConverterString.lower(identitySecretB64),
        FfiConverterData.lower(msg),uniffiCallStatus
    )
})
}
/**
 * Canonical bytes of `{logId,size,root,ts}`.
 */
public func sthMessage(sthJson: String)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypePockCoreError_lift) {
        uniffiCallStatus in
    uniffi_pock_core_fn_func_sth_message(
        FfiConverterString.lower(sthJson),uniffiCallStatus
    )
})
}
public func unlockPrf(prfSecretB64: String, wrappedAukPrfJson: String, wrappedIdentityB64: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypePockCoreError_lift) {
        uniffiCallStatus in
    uniffi_pock_core_fn_func_unlock_prf(
        FfiConverterString.lower(prfSecretB64),
        FfiConverterString.lower(wrappedAukPrfJson),
        FfiConverterString.lower(wrappedIdentityB64),uniffiCallStatus
    )
})
}
public func unlockRecovery(recoveryCode: String, wrappedRecoveryJson: String, wrappedIdentityB64: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypePockCoreError_lift) {
        uniffiCallStatus in
    uniffi_pock_core_fn_func_unlock_recovery(
        FfiConverterString.lower(recoveryCode),
        FfiConverterString.lower(wrappedRecoveryJson),
        FfiConverterString.lower(wrappedIdentityB64),uniffiCallStatus
    )
})
}
public func unlockVault(passphrase: String, secretKeyB64: String, wrappedAukJson: String, wrappedIdentityB64: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypePockCoreError_lift) {
        uniffiCallStatus in
    uniffi_pock_core_fn_func_unlock_vault(
        FfiConverterString.lower(passphrase),
        FfiConverterString.lower(secretKeyB64),
        FfiConverterString.lower(wrappedAukJson),
        FfiConverterString.lower(wrappedIdentityB64),uniffiCallStatus
    )
})
}
/**
 * k-of-n verification of a succession certificate.
 */
public func verifyCert(certJson: String, sigsJson: String, custodiansJson: String, threshold: UInt32)throws  -> Bool  {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypePockCoreError_lift) {
        uniffiCallStatus in
    uniffi_pock_core_fn_func_verify_cert(
        FfiConverterString.lower(certJson),
        FfiConverterString.lower(sigsJson),
        FfiConverterString.lower(custodiansJson),
        FfiConverterUInt32.lower(threshold),uniffiCallStatus
    )
})
}
public func verifyMessage(signPubkeyB64: String, msg: Data, sigB64: String)throws  -> Bool  {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypePockCoreError_lift) {
        uniffiCallStatus in
    uniffi_pock_core_fn_func_verify_message(
        FfiConverterString.lower(signPubkeyB64),
        FfiConverterData.lower(msg),
        FfiConverterString.lower(sigB64),uniffiCallStatus
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_pock_core_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_pock_core_checksum_func_amk_ensure() != 46705) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pock_core_checksum_func_amk_ensure_prf() != 28348) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pock_core_checksum_func_amk_sign() != 17135) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pock_core_checksum_func_amk_sign_prf() != 5710) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pock_core_checksum_func_cert_bytes() != 27852) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pock_core_checksum_func_change_passphrase() != 51764) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pock_core_checksum_func_create_vault() != 1110) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pock_core_checksum_func_create_vault_profile() != 60407) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pock_core_checksum_func_decrypt_item() != 59303) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pock_core_checksum_func_decrypt_share() != 32852) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pock_core_checksum_func_encrypt_item() != 53122) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pock_core_checksum_func_encrypt_share() != 11841) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pock_core_checksum_func_enroll_prf() != 58742) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pock_core_checksum_func_export_backup() != 61791) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pock_core_checksum_func_generate_identity() != 18383) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pock_core_checksum_func_generate_symmetric_key() != 52534) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pock_core_checksum_func_import_backup() != 46105) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pock_core_checksum_func_leaf_bytes() != 63404) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pock_core_checksum_func_message_digest() != 7596) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pock_core_checksum_func_ns_is_protected() != 59443) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pock_core_checksum_func_ns_nk_hash() != 37614) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pock_core_checksum_func_ns_protect_value() != 13292) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pock_core_checksum_func_ns_random_nk() != 65518) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pock_core_checksum_func_ns_random_recovery_code() != 54754) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pock_core_checksum_func_ns_random_salt() != 21209) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pock_core_checksum_func_ns_unprotect_value() != 21769) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pock_core_checksum_func_ns_unwrap_nk() != 1016) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pock_core_checksum_func_ns_wrap_nk() != 41336) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pock_core_checksum_func_open_symmetric() != 28250) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pock_core_checksum_func_reset_passphrase() != 15593) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pock_core_checksum_func_rotate_identity() != 55077) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pock_core_checksum_func_rotate_recovery_code() != 41278) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pock_core_checksum_func_rotate_secret_key() != 47196) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pock_core_checksum_func_seal_symmetric() != 9423) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pock_core_checksum_func_sign_message() != 28837) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pock_core_checksum_func_sth_message() != 30180) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pock_core_checksum_func_unlock_prf() != 21517) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pock_core_checksum_func_unlock_recovery() != 1413) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pock_core_checksum_func_unlock_vault() != 32690) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pock_core_checksum_func_verify_cert() != 28865) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pock_core_checksum_func_verify_message() != 18436) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsurePockCoreInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all